---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update apt repo index
      tags: always
      apt:
        update_cache: yes
      changed_when: false

    - name: Ensure community.general collection is available
      ansible.builtin.command: ansible-galaxy collection install community.general
      args:
        creates: ~/.ansible/collections/ansible_collections/community/general

    - name: Install required roles from requirements.yml
      ansible.builtin.command: ansible-galaxy install -r requirements.yml -p roles
      args:
        chdir: "{{ playbook_dir }}"
      tags: always

  roles:
    - base
    - andrewrothstein.opam
