- name: Install base dependencies
  apt:
    name:
      - ripgrep
      - fd-find
      - bat
      - git
      - php
      - zip
      - unzip
      - build-essential
      - make
      - curl
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install neovim from default repositories
  apt:
    name:
      - neovim
    state: latest
  ignore_errors: true
  register: neovim_apt_result

- name: Install neovim via snap if apt failed
  snap:
    name: nvim
    classic: true
  when: neovim_apt_result is failed

- name: clone neovim configuration
  become: false
  ansible.builtin.git:
    repo: 'https://github.com/pasanec/kickstart.nvim.git'
    dest: ~/.config/nvim
    version: ijp

- name: Create intelephense directory
  become: false
  ansible.builtin.file:
    path: ~/intelephense
    state: directory
    mode: '0755'

- name: Copy intelephense activation key
  become: false
  ansible.builtin.copy:
    content: "{{ intelephense_activation_key }}"
    dest: ~/intelephense/licence.txt
    mode: '0600'

- name: Install nvm
  become: false
  ansible.builtin.shell:
    cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
    creates: ~/.nvm/nvm.sh

- name: Install latest stable npm
  become: false
  ansible.builtin.shell:
    cmd: "source ~/.nvm/nvm.sh && nvm install --lts"
    creates: ~/.nvm/versions/node

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install Gemini CLI
  pip:
    name: google-generativeai
    state: present
