- name: Install base dependencies
  apt:
    name:
      - ripgrep
      - fd-find
      - bat
      - git
      - php
      - zip
      - unzip
      - build-essential
      - make
      - curl
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Check if neovim is already installed and get version
  command: nvim --version
  register: nvim_version_check
  failed_when: false
  changed_when: false

- name: Install neovim from GitHub releases (latest stable)
  block:
    - name: Get latest neovim release info
      uri:
        url: https://api.github.com/repos/neovim/neovim/releases/latest
        return_content: yes
      register: nvim_latest_release

    - name: Download latest neovim AppImage
      get_url:
        url: "{{ nvim_latest_release.json.assets | selectattr('name', 'equalto', 'nvim.appimage') | map(attribute='browser_download_url') | first }}"
        dest: /usr/local/bin/nvim.appimage
        mode: '0755'
        owner: root
        group: root

    - name: Create nvim symlink
      file:
        src: /usr/local/bin/nvim.appimage
        dest: /usr/local/bin/nvim
        state: link
        force: yes

  when: nvim_version_check.rc != 0 or "'v0.9.' not in nvim_version_check.stdout"

- name: clone neovim configuration
  become: false
  ansible.builtin.git:
    repo: 'https://github.com/pasanec/kickstart.nvim.git'
    dest: ~/.config/nvim
    version: ijp

- name: Create intelephense directory
  become: false
  ansible.builtin.file:
    path: ~/intelephense
    state: directory
    mode: '0755'

- name: Copy intelephense activation key
  become: false
  ansible.builtin.copy:
    content: "{{ intelephense_activation_key }}"
    dest: ~/intelephense/licence.txt
    mode: '0600'

- name: Install nvm
  become: false
  ansible.builtin.shell:
    cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
    creates: ~/.nvm/nvm.sh

- name: Install latest stable npm
  become: false
  ansible.builtin.shell:
    cmd: "source ~/.nvm/nvm.sh && nvm install --lts"
    creates: ~/.nvm/versions/node

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install Gemini CLI
  pip:
    name: google-generativeai
    state: present
