- name: Install base dependencies
  apt:
    name:
      - ripgrep
      - fd-find
      - batcat
      - git
      - php
      - zip
      - unzip
      - build-essential
      - make
      - curl
    state: latest
  when: ansible_distribution == "Ubuntu"
